project:
  type: website
  output-dir: docs
  resources:
    - google4b13fe5c076ff8e0.html
website:
  title: "Z Skigen"          # Browser tab title / metadata
  favicon: images/zslogo.png    # Sets the browser tab icon
  navbar:
    title: "ZS"              # Top-left navigation text
    right:
      - text: "ABOUT"
        href: about.qmd
      - text: "PROJECTS"
        href: projects.qmd
      - text: "BLOG"
        href: blog.qmd

format:
  html:
    theme:
      light: [united, styles.scss]
    toc: false
editor: visual