project:
  type: website
  output-dir: docs

website:
  title: "Z Skigen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: radio.qmd
        text: Radio

format:
  html:
    theme: 
      light: United
    #css: styles.css
    toc: true
    page-layout: full

editor: visual
